# Generated by Django 2.0.3 on 2020-03-25 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(max_length=100, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='商品名称')),
                ('img', models.ImageField(blank=True, default='author/default.jpg', upload_to='goods/', verbose_name='商品图片')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='出售价格')),
                ('left_num', models.IntegerField(default=0, verbose_name='商品数量')),
                ('sale_num', models.IntegerField(null=True, verbose_name='商品已卖出数量')),
            ],
            options={
                'verbose_name': '商品管理',
                'verbose_name_plural': '商品管理',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(max_length=100, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价格')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '进货管理',
                'verbose_name_plural': '进货管理',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(max_length=100, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='进货单价')),
                ('purchase_num', models.IntegerField(default=0, verbose_name='进货数量')),
                ('sum_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价格')),
                ('goods', models.ForeignKey(on_delete=True, to='app.Goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品管理',
                'verbose_name_plural': '商品管理',
            },
        ),
        migrations.CreateModel(
            name='Purchase_Record',
            fields=[
                ('id', models.AutoField(max_length=100, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价格')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '进货管理',
                'verbose_name_plural': '进货管理',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(max_length=100, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_num', models.IntegerField(default=0, verbose_name='进货数量')),
                ('sum_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价格')),
                ('goods', models.ForeignKey(on_delete=True, to='app.Goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品管理',
                'verbose_name_plural': '商品管理',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(max_length=100, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='账户')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
                ('nickname', models.CharField(max_length=30, verbose_name='昵称')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('state', models.CharField(choices=[('T', '同意登陆'), ('F', '拒绝登陆')], default='T', max_length=1, verbose_name='是否允许登陆')),
                ('identity', models.CharField(choices=[('0', '财务'), ('1', '入库员'), ('2', '收银员')], default='2', max_length=1, verbose_name='身份')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '员工管理',
                'verbose_name_plural': '员工管理',
            },
        ),
        migrations.AddField(
            model_name='purchase_record',
            name='Auditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Users', verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='purchase_record',
            name='purchaser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaser', to='app.Users', verbose_name='进货人'),
        ),
        migrations.AddField(
            model_name='purchase_record',
            name='purchases',
            field=models.ManyToManyField(to='app.Purchase', verbose_name='进货记录'),
        ),
        migrations.AddField(
            model_name='order',
            name='saler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Users', verbose_name='售货员'),
        ),
        migrations.AddField(
            model_name='order',
            name='sales',
            field=models.ManyToManyField(to='app.Sale', verbose_name='销售记录'),
        ),
    ]
