# Generated by Django 2.0.3 on 2020-03-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='sale_price',
            field=models.FloatField(verbose_name='出售价格'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sum_price',
            field=models.FloatField(verbose_name='总价格'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='cost_price',
            field=models.FloatField(verbose_name='进货单价'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='sum_price',
            field=models.FloatField(verbose_name='总价格'),
        ),
        migrations.AlterField(
            model_name='purchase_record',
            name='sum_price',
            field=models.FloatField(verbose_name='总价格'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sum_price',
            field=models.FloatField(verbose_name='总价格'),
        ),
    ]
