# Generated by Django 2.0.3 on 2020-03-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200325_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='in_money',
            field=models.FloatField(default=0, verbose_name='收钱'),
        ),
        migrations.AddField(
            model_name='order',
            name='out_money',
            field=models.FloatField(default=0, verbose_name='找零'),
        ),
    ]
