# Generated by Django 2.0.3 on 2020-03-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200327_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='sale_num',
            field=models.IntegerField(default=0, null=True, verbose_name='商品已卖出数量'),
        ),
    ]
