# Generated by Django 2.0.3 on 2020-03-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200327_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='flag',
            field=models.CharField(choices=[('T', '上架'), ('F', '下架')], default='F', max_length=1, verbose_name='是否上架'),
        ),
    ]
