# Generated by Django 2.0.3 on 2020-03-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_goods_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='cost_price',
        ),
        migrations.AddField(
            model_name='goods',
            name='cost_price',
            field=models.FloatField(default=0, verbose_name='进货单价'),
        ),
    ]
