# Generated by Django 2.0.3 on 2020-03-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200327_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '订单管理', 'verbose_name_plural': '订单管理'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': '销售记录管理', 'verbose_name_plural': '销售记录管理'},
        ),
        migrations.AddField(
            model_name='sale',
            name='profile',
            field=models.IntegerField(default=0, verbose_name='销售利润'),
        ),
    ]
