# Generated by Django 2.0.3 on 2020-03-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200327_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='profile',
            field=models.FloatField(default=0, verbose_name='利润'),
        ),
    ]
