# Generated by Django 2.0.3 on 2020-03-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_order_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='good_count',
            field=models.FloatField(default=0, verbose_name='订单商品'),
        ),
    ]
