# Generated by Django 2.0.3 on 2020-03-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_order_good_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='good_count',
            field=models.IntegerField(default=0, verbose_name='订单商品'),
        ),
    ]
