# Generated by Django 2.0.3 on 2020-03-27 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200327_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Goods', verbose_name='商品'),
        ),
    ]
