# Generated by Django 2.0.3 on 2020-03-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200327_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id'], 'verbose_name': '订单管理', 'verbose_name_plural': '订单管理'},
        ),
        migrations.AlterModelOptions(
            name='purchase_record',
            options={'ordering': ['-id'], 'verbose_name': '进货管理', 'verbose_name_plural': '进货管理'},
        ),
        migrations.RemoveField(
            model_name='goods',
            name='sale_num',
        ),
        migrations.AddField(
            model_name='goods',
            name='unit',
            field=models.CharField(default='个', max_length=5, verbose_name='单位'),
        ),
    ]
