# Generated by Django 2.0.3 on 2020-03-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200328_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='goods',
            field=models.ForeignKey(on_delete=True, to='app.Goods', verbose_name='商品'),
        ),
    ]
