# Generated by Django 2.0.3 on 2020-04-15 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20200406_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return_Record',
            fields=[
                ('id', models.AutoField(max_length=100, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_price', models.FloatField(verbose_name='总价格')),
                ('goods', models.CharField(max_length=200, verbose_name='退货商品')),
                ('Auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Users', verbose_name='审核人')),
                ('returner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='returner', to='app.Users', verbose_name='退货人')),
            ],
            options={
                'verbose_name': '退货管理',
                'verbose_name_plural': '退货管理',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(max_length=100, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='供应商名称')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('address', models.CharField(max_length=20, verbose_name='供应商地址')),
            ],
            options={
                'verbose_name': '供应商管理',
                'verbose_name_plural': '供应商管理',
            },
        ),
        migrations.CreateModel(
            name='VIP',
            fields=[
                ('id', models.AutoField(max_length=100, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30, verbose_name='昵称')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('account', models.FloatField(verbose_name='积分')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '会员管理',
                'verbose_name_plural': '会员管理',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='margin',
            field=models.FloatField(default=20, verbose_name='利润率'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='cost_price',
            field=models.FloatField(default=0, verbose_name='平均进货单价'),
        ),
    ]
