# Generated by Django 2.0.3 on 2020-04-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20200415_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='goods_price',
            field=models.FloatField(default=0, verbose_name='进货单价'),
        ),
    ]
