# Generated by Django 2.0.3 on 2020-04-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_purchase_goods_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='goods',
            field=models.ForeignKey(on_delete=True, to='app.Goods', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='purchase_record',
            name='Auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='app.Users', verbose_name='审核人'),
        ),
        migrations.AlterField(
            model_name='purchase_record',
            name='purchaser',
            field=models.ForeignKey(on_delete=True, related_name='purchaser', to='app.Users', verbose_name='进货人'),
        ),
        migrations.AlterField(
            model_name='purchase_record',
            name='supplier',
            field=models.ForeignKey(default='1', on_delete=True, to='app.Supplier', verbose_name='进货厂商'),
        ),
    ]
