# Generated by Django 2.0.3 on 2020-04-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20200415_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='return_record',
            name='goods_id_num',
            field=models.CharField(default='', max_length=200, verbose_name='退货商品和数量'),
        ),
        migrations.AddField(
            model_name='return_record',
            name='state',
            field=models.CharField(choices=[('1', '已通过审核'), ('2', '暂未审核'), ('3', '拒绝')], default='2', max_length=1, verbose_name='状态'),
        ),
    ]
