# Generated by Django 2.2.8 on 2020-04-17 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20200416_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.VIP', verbose_name='会员'),
        ),
    ]
