# Generated by Django 2.2.8 on 2020-04-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20200417_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='account',
            field=models.FloatField(default=0, verbose_name='积分'),
        ),
    ]
