# Generated by Django 2.2.8 on 2020-04-17 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20200417_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='vip',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.VIP', verbose_name='会员'),
        ),
    ]
