# Generated by Django 2.2.8 on 2020-04-17 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20200417_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.VIP', verbose_name='会员'),
        ),
    ]
