# Generated by Django 2.2.8 on 2020-04-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_order_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='phone',
            field=models.CharField(max_length=11, unique=True, verbose_name='联系电话'),
        ),
    ]
